var lst_games = [
    {"name": "KINGDOM HEARTS III",
     "url":"https://images.igdb.com/igdb/image/upload/t_thumb/co1tqk.jpg",
      "synopsys":"Jeu vidéo de Square Enix  sur PC, PlayStation 4 et Xbox One"  },
    { "name": "It Takes Two (2021)",
     "url": "https://media.senscritique.com/media/000019970439/150/It_Takes_Two.jpg",
     "synopsys":"Jeu vidéo de Hazelight, Josef Fares et Electronic Arts sur PC, PlayStation 5, Xbox Series X/S, PlayStation 4 et Xbox One" },
    {  "name": "Crash Bandicoot 4 : It's About Time (2020)",
     "url": "https://media.senscritique.com/media/000019597728/150/Crash_Bandicoot_4_It_s_About_Time.png" ,
     "synopsys":"Jeu vidéo de Toys For Bob et Activision sur PlayStation 5, Xbox Series X/S, Nintendo Switch, PlayStation 4, Xbox One et PC"},
    {  "name": "Super Mario 3D World + Bowser's Fury (2021)",
     "url": "https://media.senscritique.com/media/000019855048/150/Super_Mario_3D_World_Bowser_s_Fury.png",
     "synopsys":"Jeu vidéo de Nintendo EPD et Nintendo sur Nintendo Switch" },
    {  "name": "Cyberpunk 2077 (2020)",
     "url": "https://media.senscritique.com/media/000019358303/150/Cyberpunk_2077.png" ,
     "synopsys":"Jeu vidéo de CD Projekt RED et CD Projekt sur PC, PlayStation 4, Xbox One, PlayStation 5, Xbox Series X/S et Stadia"},
    {  "name": "Observer : System Redux (2020)",
     "url": "https://media.senscritique.com/media/000019442919/150/Observer_System_Redux.jpg",
     "synopsys":"Jeu vidéo de Bloober Team et Aspyr sur PlayStation 5, PC et Xbox Series X/S" },
    {  "name": "Ghostrunner (2020)",
     "url": "https://media.senscritique.com/media/000019668502/150/Ghostrunner.png" ,
     "synopsys":"Jeu vidéo de One More Level et All in! Games sur PC, PlayStation 4, Nintendo Switch et Xbox One"},
    {  "name": "G-String (2020)",
     "url": "https://media.senscritique.com/media/000019650715/150/G_String.jpg" ,
     "synopsys":"Jeu vidéo de Eyaura et LunchHouse Software sur PC"},
    {  "name": "Mafia : Definitive Edition (2020)",
     "url": "https://media.senscritique.com/media/000019609926/150/Mafia_Definitive_Edition.png" ,
     "synopsys":"Jeu vidéo de Hangar 13 et 2K Games sur PC, PlayStation 4 et Xbox One"},
    {  "name": "Cyber Hook (2020)",
     "url": "https://media.senscritique.com/media/000019846899/150/Cyber_Hook.jpg" ,
     "synopsys":"Jeu vidéo de Blazing Stick et Graffiti Games sur Nintendo Switch et PC"},
    {  "name": "Serious Sam 4 (2020)",
     "url": "https://media.senscritique.com/media/000019388314/150/Serious_Sam_4.png" ,
     "synopsys":"Jeu vidéo de Croteam et Devolver Digital sur PC, PlayStation 4, Xbox One et Stadia"},
    {  "name": "Horizon : Zero Dawn (2017)",
     "url": "https://media.senscritique.com/media/000015791257/150/Horizon_Zero_Dawn.jpg" ,
     "synopsys":"Jeu vidéo de Guerilla Games et Sony Interactive Entertainment sur PlayStation 4 et PC"},
    {  "name": "Ghost of Tsushima (2020)",
     "url": "https://media.senscritique.com/media/000019091627/150/Ghost_of_Tsushima.png",
     "synopsys":"Jeu vidéo de Sucker Punch et Sony Interactive Entertainment sur PlayStation 4 et PlayStation 5" },
    {  "name": " SUPERHOT : Mind Control Delete (2020)",
     "url": "https://media.senscritique.com/media/000019485304/150/SUPERHOT_Mind_Control_Delete.jpg",
     "synopsys":"Jeu vidéo de Superhot Team sur PC, PlayStation 4 et Xbox One" },
    {  "name": "The Last of Us Part II (2020)",
     "url": "https://media.senscritique.com/media/000018788867/150/The_Last_of_Us_Part_II.png" ,
     "synopsys":"Jeu vidéo de Naughty Dog et Sony Interactive Entertainment sur PlayStation 4 et PlayStation 5"},
    {  "name": "Half-Life : Alyx (2020)",
     "url": "https://media.senscritique.com/media/000019240424/150/Half_Life_Alyx.png",
     "synopsys":"Jeu vidéo de Valve sur Linux et PC" },
    {  "name": "Doom Eternal (2020)",
     "url": "https://media.senscritique.com/media/000019302995/150/Doom_Eternal.png" ,
     "synopsys":"Jeu vidéo de id Software et Bethesda Softworks sur PC, PlayStation 4, Xbox One, Nintendo Switch, Stadia, PlayStation 5 et Xbox Series X/S"},
    {  "name": "Elderborn (2020)",
     "url": "https://media.senscritique.com/media/000019521561/150/Elderborn.jpg" ,
     "synopsys":"Jeu vidéo de Hyperstrange sur PC"},
    {  "name": "Life is Strange 2 (2019)",
     "url": "https://media.senscritique.com/media/000017987121/150/Life_is_Strange_2.jpg",
     "synopsys":"Jeu vidéo de Dontnod Entertainment et Square Enix sur PC, PlayStation 4, Xbox One, Mac et Linux" },
    {  "name": "Red Dead Redemption II (2018)",
     "url": "https://media.senscritique.com/media/000017772625/150/Red_Dead_Redemption_II.png",
     "synopsys":"Jeu vidéo de Rockstar North, Rockstar San Diego et Rockstar Games sur PlayStation 4, Xbox One, PC et Stadia" },
    {  "name": "Control (2019)",
     "url": "https://media.senscritique.com/media/000019104448/150/Control.png" ,
     "synopsys":"Jeu vidéo de Remedy Entertainment et 505 Games sur PlayStation 4, Xbox One, PC, PlayStation 5, Xbox Series X/S et Nintendo Switch"},
    {  "name": "Ion Fury (2019)",
     "url": "https://media.senscritique.com/media/000019718218/150/Ion_Fury.png",
     "synopsys":"Jeu vidéo de Voidpoint et 3D Realms sur PlayStation 4, Nintendo Switch, Xbox One, PC et Linux" },
    {  "name": "Wolfenstein : Youngblood (2019)",
     "url": "https://media.senscritique.com/media/000018437621/150/Wolfenstein_Youngblood.png" ,
     "synopsys":"Jeu vidéo de MachineGames, Arkane Studios et Bethesda Softworks sur PC, PlayStation 4, Xbox One, Nintendo Switch et Stadia"},
    {  "name": "Super Mario Maker 2 (2019)",
     "url": "https://media.senscritique.com/media/000019855684/150/Super_Mario_Maker_2.png",
     "synopsys":"Jeu vidéo de Nintendo EPD et Nintendo sur Nintendo Switch" },
    {  "name": "Amid Evil (2019)",
     "url": "https://media.senscritique.com/media/000018614270/150/Amid_Evil.jpg",
     "synopsys":"Jeu vidéo de Indefatigable et New Blood Interactive sur PC et Nintendo Switch" },
    {  "name": "The Walking Dead : The Telltale Series - The Final Season (2018)",
     "url": "https://media.senscritique.com/media/000017797794/150/The_Walking_Dead_The_Telltale_Series_The_Final_Season.jpg",
     "synopsys":"Jeu vidéo de Skybound Games et Telltale Games sur PC, PlayStation 4, Xbox One, Nintendo Switch, iPad, iPhone, Android et Mac" }
]
$('#result').html('');
$('#state').val('');
var searchField = $('#search').val();
var expression = new RegExp(searchField, "i");
$.each(lst_games, function (key, value) {
    if (value.url.search(expression) != -1) {
        $('#result').append(
            '<tr><div>'
            +'<td><img class="image_games" src= ' + value.url + '></img></td>'+
        '<td><h3>' +value.name + '</h3>'+ '<div>' +value.synopsys + '</div>'+'</td>'
        +'</div></tr>');
    }
});
